baseURL = "https://localhost.com"
languageCode = 'en-us'
title = 'Leon Lit'
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[pagination]
pagelimit = 10

[markup.tableOfContents]
  startLevel = 2
  endLevel = 4

[taxonomies]
  tag = "tags"
  category = "categories"
  year = "years"